# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sn.proto',
  package='reverse',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08sn.proto\x12\x07reverse\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\":\n\x08PostData\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06idpost\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"0\n\rResponseLenta\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06idpost\x18\x02 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xcb\x02\n\x06SocNet\x12+\n\x02\x44o\x12\x10.reverse.Request\x1a\x11.reverse.Response\"\x00\x12\x35\n\x0bUserAddPost\x12\x11.reverse.PostData\x1a\x11.reverse.Response\"\x00\x12\x36\n\x0cUserLikePost\x12\x11.reverse.PostData\x1a\x11.reverse.Response\"\x00\x12\x39\n\x0fUserCommentPost\x12\x11.reverse.PostData\x1a\x11.reverse.Response\"\x00\x12\x31\n\x08UserList\x12\x10.reverse.Request\x1a\x11.reverse.Response\"\x00\x12\x37\n\tUserLenta\x12\x10.reverse.Request\x1a\x16.reverse.ResponseLenta\"\x00\x62\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='reverse.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='reverse.Request.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=47,
)


_POSTDATA = _descriptor.Descriptor(
  name='PostData',
  full_name='reverse.PostData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='reverse.PostData.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idpost', full_name='reverse.PostData.idpost', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='reverse.PostData.body', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=107,
)


_RESPONSELENTA = _descriptor.Descriptor(
  name='ResponseLenta',
  full_name='reverse.ResponseLenta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='reverse.ResponseLenta.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idpost', full_name='reverse.ResponseLenta.idpost', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=157,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='reverse.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='reverse.Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=186,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['PostData'] = _POSTDATA
DESCRIPTOR.message_types_by_name['ResponseLenta'] = _RESPONSELENTA
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'sn_pb2'
  # @@protoc_insertion_point(class_scope:reverse.Request)
  })
_sym_db.RegisterMessage(Request)

PostData = _reflection.GeneratedProtocolMessageType('PostData', (_message.Message,), {
  'DESCRIPTOR' : _POSTDATA,
  '__module__' : 'sn_pb2'
  # @@protoc_insertion_point(class_scope:reverse.PostData)
  })
_sym_db.RegisterMessage(PostData)

ResponseLenta = _reflection.GeneratedProtocolMessageType('ResponseLenta', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSELENTA,
  '__module__' : 'sn_pb2'
  # @@protoc_insertion_point(class_scope:reverse.ResponseLenta)
  })
_sym_db.RegisterMessage(ResponseLenta)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'sn_pb2'
  # @@protoc_insertion_point(class_scope:reverse.Response)
  })
_sym_db.RegisterMessage(Response)



_SOCNET = _descriptor.ServiceDescriptor(
  name='SocNet',
  full_name='reverse.SocNet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=189,
  serialized_end=520,
  methods=[
  _descriptor.MethodDescriptor(
    name='Do',
    full_name='reverse.SocNet.Do',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserAddPost',
    full_name='reverse.SocNet.UserAddPost',
    index=1,
    containing_service=None,
    input_type=_POSTDATA,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserLikePost',
    full_name='reverse.SocNet.UserLikePost',
    index=2,
    containing_service=None,
    input_type=_POSTDATA,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserCommentPost',
    full_name='reverse.SocNet.UserCommentPost',
    index=3,
    containing_service=None,
    input_type=_POSTDATA,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserList',
    full_name='reverse.SocNet.UserList',
    index=4,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserLenta',
    full_name='reverse.SocNet.UserLenta',
    index=5,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSELENTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOCNET)

DESCRIPTOR.services_by_name['SocNet'] = _SOCNET

# @@protoc_insertion_point(module_scope)
